Se agrego Funcionalidad a todas las busquedas
JohanaMontenegro/TPFinal2C pull request #4
Opened 2022-10-30 15:32 UTC by FacundoMamonde

2022-10-30 22:02 UTC, NahuFalconaro commented on src/components/Candidatos.vue
> +  <CandidatosSearchComponent @searchByName="searchByName($event)" @searchBySurname="searchBySurname($event)"
En esta seccion que se quiso lograr?

2022-10-30 22:03 UTC, NahuFalconaro reviewed
Agregar mas descripcion a los PR. Bien separado, podria mejorarse la componentizacion.

2022-10-30 22:03 UTC, NahuFalconaro approved these changes

2022-10-30 22:08 UTC, FacundoMamonde commented on src/components/Candidatos.vue
> +  <CandidatosSearchComponent @searchByName="searchByName($event)" @searchBySurname="searchBySurname($event)"
Debe ser resto de codigo no usado, ahora lo corrijo

2022-10-31 14:38 UTC, SofiZ2001 requested changes
Subir los cambios del comment que hico Nahu y ya se mergea

2022-10-31 19:02 UTC, FacundoMamonde commented on src/components/Candidatos.vue
> +  <CandidatosSearchComponent @searchByName="searchByName($event)" @searchBySurname="searchBySurname($event)"
Ahi hice otro commit

2022-10-31 20:00 UTC, SofiZ2001 approved these changes

2022-10-31 20:00 UTC, merged